title: Cecilia Putri
markdown: kramdown
url: "https://CeciliaPutri131.github.io"
baseurl: "/"

# for atom feed
author:
  name: Cecilia Putri
  email: 

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-google-search-console-verification-file
  
paginate: 4
paginate_path: "/page:num/"

ganalytics: 
google_search_console:
       verification_file_code: 
google_site_verification: 
enable_google_verification: true
  

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
